version: '3.8'

services:
  trackmaster:
    build: .
    image: trackmaster-pro:latest
    container_name: trackmaster-pro
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - DB_PATH=/app/data/trackmaster.db
      - VITE_GOOGLE_SHEETS_SCRIPT_URL=https://script.google.com/macros/s/AKfycbyxxnxVyxClMw_TpJ3n720CjHXeBNiL2gWyW2hLkXSq15pY-uWztMnF7kyor4HxUOKN/exec
